// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "ui_Screen1.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_mosuqe_png);    // assets/mosuqe.png
LV_IMG_DECLARE(ui_img_nowifi_png);    // assets/nowifi.png
LV_IMG_DECLARE(ui_img_wifi_png);    // assets/wifi.png
LV_IMG_DECLARE(ui_img_650607941);    // assets/keyboard-open.png
LV_IMG_DECLARE(ui_img_1867271658);    // assets/video-time.png
LV_IMG_DECLARE(ui_img_help_png);    // assets/help.png
LV_IMG_DECLARE(ui_img_1308353594);    // assets/setting-2.png

// FONTS
LV_FONT_DECLARE(ui_font_NotoSans10);
LV_FONT_DECLARE(ui_font_NotoSans12);
LV_FONT_DECLARE(ui_font_NotoSans14);
LV_FONT_DECLARE(ui_font_NotoSans18);
LV_FONT_DECLARE(ui_font_NotoSans20);
LV_FONT_DECLARE(ui_font_NotoSans24);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
