// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

// void ui_event_comp_mainContentContainer_Image3(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t ** comp_mainContentContainer = lv_event_get_user_data(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_switch_theme(UI_THEME_DEFAULT);
//     }
// }

// void ui_event_comp_mainContentContainer_Image2(lv_event_t * e)
// {
//     lv_event_code_t event_code = lv_event_get_code(e);
//     lv_obj_t ** comp_mainContentContainer = lv_event_get_user_data(e);

//     if(event_code == LV_EVENT_CLICKED) {
//         _ui_switch_theme(UI_THEME_LIGHT);
//     }
// }

// COMPONENT mainContentContainer

lv_obj_t * ui_mainContentContainer_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_mainContentContainer;
    cui_mainContentContainer = lv_obj_create(comp_parent);
    lv_obj_remove_style_all(cui_mainContentContainer);
    lv_obj_set_width(cui_mainContentContainer, 480);
    lv_obj_set_height(cui_mainContentContainer, 320);
    lv_obj_set_align(cui_mainContentContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_mainContentContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(cui_mainContentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image1;
    cui_Image1 = lv_img_create(cui_mainContentContainer);
    lv_img_set_src(cui_Image1, &ui_img_mosuqe_png);
    lv_obj_set_width(cui_Image1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image1, 71);
    lv_obj_set_y(cui_Image1, 39);
    lv_obj_add_flag(cui_Image1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(cui_Image1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image3;
    cui_Image3 = lv_img_create(cui_mainContentContainer);
    lv_obj_set_width(cui_Image3, LV_SIZE_CONTENT);   /// 3
    lv_obj_set_height(cui_Image3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image3, 32);
    lv_obj_set_y(cui_Image3, 7);
    lv_obj_add_flag(cui_Image3, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(cui_Image3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Image2;
    cui_Image2 = lv_img_create(cui_mainContentContainer);
    lv_obj_set_width(cui_Image2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Image2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Image2, 7);
    lv_obj_set_y(cui_Image2, 8);
    lv_obj_add_flag(cui_Image2, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_clear_flag(cui_Image2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Panel5;
    cui_Panel5 = lv_obj_create(cui_mainContentContainer);
    lv_obj_set_width(cui_Panel5, 59);
    lv_obj_set_height(cui_Panel5, 264);
    lv_obj_set_x(cui_Panel5, 5);
    lv_obj_set_y(cui_Panel5, 46);
    lv_obj_clear_flag(cui_Panel5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Panel5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_Panel5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_Panel5, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label1;
    cui_Label1 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label1, 0);
    lv_obj_set_y(cui_Label1, -20);
    lv_obj_set_align(cui_Label1, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label1, "الفجر");
    lv_obj_set_style_text_color(cui_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label2;
    cui_Label2 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label2, 0);
    lv_obj_set_y(cui_Label2, 5);
    lv_obj_set_align(cui_Label2, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label2, "06:43");
    lv_obj_set_style_text_color(cui_Label2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label2, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label3, 0);
    lv_obj_set_y(cui_Label3, 60);
    lv_obj_set_align(cui_Label3, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label3, "الظهر");
    lv_obj_set_style_text_color(cui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label4;
    cui_Label4 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label4, 0);
    lv_obj_set_y(cui_Label4, 85);
    lv_label_set_text(cui_Label4, "13:38");
    lv_obj_set_style_text_color(cui_Label4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label4, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label5;
    cui_Label5 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label5, 0);
    lv_obj_set_y(cui_Label5, 100);
    lv_obj_set_align(cui_Label5, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label5, "العصر");
    lv_obj_set_style_text_color(cui_Label5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label6;
    cui_Label6 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label6, 0);
    lv_obj_set_y(cui_Label6, 125);
    lv_obj_set_align(cui_Label6, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label6, "13:38");
    lv_obj_set_style_text_color(cui_Label6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label6, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label7;
    cui_Label7 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label7, 0);
    lv_obj_set_y(cui_Label7, 140);
    lv_obj_set_align(cui_Label7, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label7, "المغرب");
    lv_obj_set_style_text_color(cui_Label7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label7, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label8;
    cui_Label8 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label8, 0);
    lv_obj_set_y(cui_Label8, 165);
    lv_obj_set_align(cui_Label8, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label8, "18:44");
    lv_obj_set_style_text_color(cui_Label8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label8, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label9;
    cui_Label9 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label9, 0);
    lv_obj_set_y(cui_Label9, 180);
    lv_obj_set_align(cui_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label9, "العشاء");
    lv_obj_set_style_text_color(cui_Label9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label9, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label10;
    cui_Label10 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label10, 0);
    lv_obj_set_y(cui_Label10, 205);
    lv_obj_set_align(cui_Label10, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label10, "18:44");
    lv_obj_set_style_text_color(cui_Label10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label10, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label11;
    cui_Label11 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label11, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label11, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label11, 0);
    lv_obj_set_y(cui_Label11, 20);
    lv_obj_set_align(cui_Label11, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label11, "الشروق");
    lv_obj_set_style_text_color(cui_Label11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label11, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label11, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Label12;
    cui_Label12 = lv_label_create(cui_Panel5);
    lv_obj_set_width(cui_Label12, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label12, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_Label12, 0);
    lv_obj_set_y(cui_Label12, 45);
    lv_obj_set_align(cui_Label12, LV_ALIGN_TOP_MID);
    lv_label_set_text(cui_Label12, "06:43");
    lv_obj_set_style_text_color(cui_Label12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label12, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label12, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Container21;
    cui_Container21 = lv_obj_create(cui_mainContentContainer);
    lv_obj_remove_style_all(cui_Container21);
    lv_obj_set_width(cui_Container21, 324);
    lv_obj_set_height(cui_Container21, 43);
    lv_obj_set_x(cui_Container21, 57);
    lv_obj_set_y(cui_Container21, 0);
    lv_obj_clear_flag(cui_Container21, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_labelDayofWeek;
    cui_labelDayofWeek = lv_label_create(cui_Container21);
    lv_obj_set_width(cui_labelDayofWeek, 53);
    lv_obj_set_height(cui_labelDayofWeek, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labelDayofWeek, 280);
    lv_obj_set_y(cui_labelDayofWeek, 0);
    lv_obj_set_align(cui_labelDayofWeek, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(cui_labelDayofWeek, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_labelDayofWeek, "");
    lv_obj_set_style_text_align(cui_labelDayofWeek, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_labelDayofWeek, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(cui_labelDayofWeek, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_labelDayofWeek, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lableMonth;
    cui_lableMonth = lv_label_create(cui_Container21);
    lv_obj_set_width(cui_lableMonth, 100);
    lv_obj_set_height(cui_lableMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lableMonth, 135);
    lv_obj_set_y(cui_lableMonth, 1);
    lv_obj_set_align(cui_lableMonth, LV_ALIGN_LEFT_MID);
    lv_label_set_long_mode(cui_lableMonth, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(cui_lableMonth, "");
    lv_obj_set_style_text_align(cui_lableMonth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_lableMonth, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labelDayofMonth;
    cui_labelDayofMonth = lv_label_create(cui_Container21);
    lv_obj_set_width(cui_labelDayofMonth, 25);
    lv_obj_set_height(cui_labelDayofMonth, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labelDayofMonth, 245);
    lv_obj_set_y(cui_labelDayofMonth, 0);
    lv_obj_set_align(cui_labelDayofMonth, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_labelDayofMonth, "");
    lv_obj_set_style_text_align(cui_labelDayofMonth, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_labelDayofMonth, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(cui_labelDayofMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(cui_labelDayofMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(cui_labelDayofMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(cui_labelDayofMonth, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_lableYear;
    cui_lableYear = lv_label_create(cui_Container21);
    lv_obj_set_width(cui_lableYear, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_lableYear, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_lableYear, 75);
    lv_obj_set_y(cui_lableYear, -1);
    lv_obj_set_align(cui_lableYear, LV_ALIGN_LEFT_MID);
    lv_label_set_text(cui_lableYear, "");
    lv_obj_set_style_text_font(cui_lableYear, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_labelClock;
    cui_labelClock = lv_label_create(cui_mainContentContainer);
    lv_obj_set_width(cui_labelClock, 55);
    lv_obj_set_height(cui_labelClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_labelClock, 184);
    lv_obj_set_y(cui_labelClock, -140);
    lv_obj_set_align(cui_labelClock, LV_ALIGN_CENTER);
    lv_label_set_text(cui_labelClock, "");
    lv_obj_set_style_text_font(cui_labelClock, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_MAINCONTENTCONTAINER_NUM);
    children[UI_COMP_MAINCONTENTCONTAINER_MAINCONTENTCONTAINER] = cui_mainContentContainer;
    children[UI_COMP_MAINCONTENTCONTAINER_IMAGE1] = cui_Image1;
    children[UI_COMP_MAINCONTENTCONTAINER_IMAGE3] = cui_Image3;
    children[UI_COMP_MAINCONTENTCONTAINER_IMAGE2] = cui_Image2;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5] = cui_Panel5;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL1] = cui_Label1;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL2] = cui_Label2;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL3] = cui_Label3;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL4] = cui_Label4;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL5] = cui_Label5;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL6] = cui_Label6;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL7] = cui_Label7;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL8] = cui_Label8;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL9] = cui_Label9;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL10] = cui_Label10;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL11] = cui_Label11;
    children[UI_COMP_MAINCONTENTCONTAINER_PANEL5_LABEL12] = cui_Label12;
    children[UI_COMP_MAINCONTENTCONTAINER_CONTAINER21] = cui_Container21;
    children[UI_COMP_MAINCONTENTCONTAINER_CONTAINER21_LABELDAYOFWEEK] = cui_labelDayofWeek;
    children[UI_COMP_MAINCONTENTCONTAINER_CONTAINER21_LABLEMONTH] = cui_lableMonth;
    children[UI_COMP_MAINCONTENTCONTAINER_CONTAINER21_LABELDAYOFMONTH] = cui_labelDayofMonth;
    children[UI_COMP_MAINCONTENTCONTAINER_CONTAINER21_LABLEYEAR] = cui_lableYear;
    children[UI_COMP_MAINCONTENTCONTAINER_LABELCLOCK] = cui_labelClock;
    lv_obj_add_event_cb(cui_mainContentContainer, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_mainContentContainer, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Image3, ui_event_comp_mainContentContainer_Image3, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Image2, ui_event_comp_mainContentContainer_Image2, LV_EVENT_ALL, children);
    ui_comp_mainContentContainer_create_hook(cui_mainContentContainer);
    return cui_mainContentContainer;
}

