// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

void get_the_selected_calender(lv_event_t * e);
void save_clock_setting(lv_event_t * e);
void saveRelayName(lv_event_t * e);
void relay_1_control_hanlde(lv_event_t * e);
void relay_2_control_hanlde(lv_event_t * e);
void relay_3_control_hanlde(lv_event_t * e);
void relay_4_control_hanlde(lv_event_t * e);
void relay_5_control_hanlde(lv_event_t * e);
void relay_6_control_hanlde(lv_event_t * e);
void relay_7_control_hanlde(lv_event_t * e);
void relay_8_control_hanlde(lv_event_t * e);
void search_wifi(lv_event_t * e);
void connect_to_wifi(lv_event_t * e);
void canele_connection(lv_event_t * e);
void change_keyboard_function(lv_event_t * e);
void go_to_main_screen(lv_event_t * e);
void go_to_setting_screen(lv_event_t * e);
void go_to_program_screen(lv_event_t *e);
void handle_wifi_selected(lv_event_t * e);


#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
