// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_settingContentContainer = NULL;
lv_obj_t * ui_TabView2 = NULL;
lv_obj_t * ui_TabPage2 = NULL;
lv_obj_t * ui_rollerMinuteSetting = NULL;
lv_obj_t * ui_rollerHourSetting = NULL;
lv_obj_t * ui_RollerTimeZone = NULL;
lv_obj_t * ui_Label13 = NULL;
lv_obj_t * ui_Label14 = NULL;
lv_obj_t * ui_Label15 = NULL;
lv_obj_t * ui_Label16 = NULL;
lv_obj_t * ui_CheckBoxAutoClock = NULL;
lv_obj_t * ui_Calendar2 = NULL;
lv_obj_t * ui_Label18 = NULL;
lv_obj_t * ui_ButtonSettingClock = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_TabPage3 = NULL;
lv_obj_t * ui_Container2 = NULL;
lv_obj_t * ui_PanelRelayInfo1 = NULL;
lv_obj_t * ui_LabelRelayNameSetting1 = NULL;
lv_obj_t * ui_PanelRelayInfo2 = NULL;
lv_obj_t * ui_LabelRelayNameSetting2 = NULL;
lv_obj_t * ui_PanelRelayInfo3 = NULL;
lv_obj_t * ui_LabelRelayNameSetting3 = NULL;
lv_obj_t * ui_PanelRelayInfo4 = NULL;
lv_obj_t * ui_LabelRelayNameSetting4 = NULL;
lv_obj_t * ui_PanelRelayInfo5 = NULL;
lv_obj_t * ui_LabelRelayNameSetting5 = NULL;
lv_obj_t * ui_PanelRelayInfo6 = NULL;
lv_obj_t * ui_LabelRelayNameSetting6 = NULL;
lv_obj_t * ui_PanelRelayInfo7 = NULL;
lv_obj_t * ui_LabelRelayNameSetting7 = NULL;
lv_obj_t * ui_PanelRelayInfo8 = NULL;
lv_obj_t * ui_LabelRelayNameSetting8 = NULL;
lv_obj_t * ui_PanelRelaySetting = NULL;
lv_obj_t * ui_DropdownRelayNumber = NULL;
lv_obj_t * ui_TextAreaRelayName = NULL;
lv_obj_t * ui_ButtonRelaySave = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Panel2 = NULL;
lv_obj_t * ui_Label39 = NULL;
lv_obj_t * ui_Container3 = NULL;
lv_obj_t * ui_SwitchAutoRelay1 = NULL;
lv_obj_t * ui_LabelControlState1 = NULL;
lv_obj_t * ui_Container4 = NULL;
lv_obj_t * ui_SwitchAutoRelay2 = NULL;
lv_obj_t * ui_LabelControlState2 = NULL;
lv_obj_t * ui_Container5 = NULL;
lv_obj_t * ui_SwitchAutoRelay3 = NULL;
lv_obj_t * ui_LabelControlState3 = NULL;
lv_obj_t * ui_Container6 = NULL;
lv_obj_t * ui_SwitchAutoRelay4 = NULL;
lv_obj_t * ui_LabelControlState4 = NULL;
lv_obj_t * ui_Container7 = NULL;
lv_obj_t * ui_SwitchAutoRelay5 = NULL;
lv_obj_t * ui_LabelControlState5 = NULL;
lv_obj_t * ui_Container8 = NULL;
lv_obj_t * ui_SwitchAutoRelay6 = NULL;
lv_obj_t * ui_LabelControlState6 = NULL;
lv_obj_t * ui_Container9 = NULL;
lv_obj_t * ui_SwitchAutoRelay7 = NULL;
lv_obj_t * ui_LabelControlState7 = NULL;
lv_obj_t * ui_Container10 = NULL;
lv_obj_t * ui_SwitchAutoRelay8 = NULL;
lv_obj_t * ui_LabelControlState8 = NULL;
lv_obj_t * ui_TabPage4 = NULL;
lv_obj_t * ui_Button6 = NULL;
lv_obj_t * ui_Label10 = NULL;
lv_obj_t * ui_Label30 = NULL;
lv_obj_t * ui_KeyboardSSIDPassword = NULL;
lv_obj_t * ui_PanelSSIDPassword = NULL;
lv_obj_t * ui_LabelSSID = NULL;
lv_obj_t * ui_TextAreaSSIPassword = NULL;
lv_obj_t * ui_Button7 = NULL;
lv_obj_t * ui_Label34 = NULL;
lv_obj_t * ui_Button8 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_KeyboardRelayName = NULL;
lv_obj_t * ui_programContentContainer = NULL;
lv_obj_t * ui_Button1 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_ContainerProgram = NULL;
lv_obj_t * ui_mainContentContainer = NULL;
lv_obj_t * ui_Image8 = NULL;
lv_obj_t * ui_Panel1 = NULL;
lv_obj_t * ui_Label17 = NULL;
lv_obj_t * ui_Label19 = NULL;
lv_obj_t * ui_Label20 = NULL;
lv_obj_t * ui_Label21 = NULL;
lv_obj_t * ui_Label22 = NULL;
lv_obj_t * ui_Label23 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Label27 = NULL;
lv_obj_t * ui_Label28 = NULL;
lv_obj_t * ui_Label29 = NULL;
lv_obj_t * ui_Container1 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_imageNoWiFi = NULL;
lv_obj_t * ui_imageWiFi = NULL;
lv_obj_t * ui_labelClock = NULL;
lv_obj_t * ui_PanelInfo = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label37 = NULL;
lv_obj_t * ui_Label38 = NULL;
lv_obj_t * ui_mainScreenButton = NULL;
lv_obj_t * ui_Image4 = NULL;
lv_obj_t * ui_programSettingButton = NULL;
lv_obj_t * ui_Image5 = NULL;
lv_obj_t * ui_aboutButton = NULL;
lv_obj_t * ui_Image6 = NULL;
lv_obj_t * ui_settingButton = NULL;
lv_obj_t * ui_Image7 = NULL;
// event funtions
void ui_event_Calendar2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        get_the_selected_calender(e);
    }
}

void ui_event_Label18(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Calendar2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_ButtonSettingClock(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        save_clock_setting(e);
    }
}

void ui_event_TextAreaRelayName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardRelayName, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardRelayName, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_ButtonRelaySave(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        saveRelayName(e);
    }
}

void ui_event_SwitchAutoRelay1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_1_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_2_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_3_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_4_control_hanlde(e);
        (e);
    }
}

void ui_event_SwitchAutoRelay5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_5_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_6_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_7_control_hanlde(e);
    }
}

void ui_event_SwitchAutoRelay8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        relay_8_control_hanlde(e);
    }
}

void ui_event_Button6(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        search_wifi(e);
    }
}

void ui_event_TextAreaSSIPassword(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_KeyboardSSIDPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_KeyboardSSIDPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Button7(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        connect_to_wifi(e);
    }
}

void ui_event_Button8(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelSSIDPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_KeyboardSSIDPassword, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        canele_connection(e);
    }
}

void ui_event_KeyboardRelayName(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        change_keyboard_function(e);
    }
}

void ui_event_mainScreenButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        go_to_main_screen(e);
    }
}

void ui_event_programSettingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        go_to_program_screen(e);
    }
}

void ui_event_aboutButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_PanelInfo, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

void ui_event_settingButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        go_to_setting_screen(e);
        (e);
    }
}

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settingContentContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_settingContentContainer);
    lv_obj_set_width(ui_settingContentContainer, 480);
    lv_obj_set_height(ui_settingContentContainer, 320);
    lv_obj_set_align(ui_settingContentContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settingContentContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_settingContentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_TabView2 = lv_tabview_create(ui_settingContentContainer, LV_DIR_TOP, 25);
    lv_obj_set_width(ui_TabView2, 480);
    lv_obj_set_height(ui_TabView2, 311);
    lv_obj_set_x(ui_TabView2, 0);
    lv_obj_set_y(ui_TabView2, 6);
    lv_obj_clear_flag(ui_TabView2, LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_bg_color(ui_TabView2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_TabView2, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(ui_TabView2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabView2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabView2, &ui_font_NotoSans20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0xFFFFFF),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(lv_tabview_get_tab_btns(ui_TabView2), &ui_font_NotoSans10,  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_TabView2), lv_color_hex(0x000000),
                              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_TabView2), 255,  LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage2 = lv_tabview_add_tab(ui_TabView2, "الوقت والتاريخ");
    lv_obj_clear_flag(ui_TabPage2, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_text_color(ui_TabPage2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TabPage2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TabPage2, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerMinuteSetting = lv_roller_create(ui_TabPage2);
    lv_roller_set_options(ui_rollerMinuteSetting,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59",
                          LV_ROLLER_MODE_NORMAL);
    lv_obj_set_width(ui_rollerMinuteSetting, 45);
    lv_obj_set_height(ui_rollerMinuteSetting, 60);
    lv_obj_set_x(ui_rollerMinuteSetting, 265);
    lv_obj_set_y(ui_rollerMinuteSetting, 10);
    lv_obj_set_style_text_color(ui_rollerMinuteSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerMinuteSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_rollerMinuteSetting, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerMinuteSetting, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerMinuteSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_rollerMinuteSetting, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerMinuteSetting, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_rollerHourSetting = lv_roller_create(ui_TabPage2);
    lv_roller_set_options(ui_rollerHourSetting,
                          "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23",
                          LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_rollerHourSetting, 12, LV_ANIM_OFF);
    lv_obj_set_width(ui_rollerHourSetting, 45);
    lv_obj_set_height(ui_rollerHourSetting, 60);
    lv_obj_set_x(ui_rollerHourSetting, 205);
    lv_obj_set_y(ui_rollerHourSetting, 10);
    lv_obj_set_style_text_color(ui_rollerHourSetting, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_rollerHourSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_rollerHourSetting, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_rollerHourSetting, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_rollerHourSetting, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RollerTimeZone = lv_roller_create(ui_TabPage2);
    lv_roller_set_options(ui_RollerTimeZone, "-3\n-2\n-1\n0\n+1\n+2\n+3", LV_ROLLER_MODE_NORMAL);
    lv_roller_set_selected(ui_RollerTimeZone, 3, LV_ANIM_OFF);
    lv_obj_set_width(ui_RollerTimeZone, 40);
    lv_obj_set_height(ui_RollerTimeZone, 60);
    lv_obj_set_x(ui_RollerTimeZone, 260);
    lv_obj_set_y(ui_RollerTimeZone, 150);
    lv_obj_set_style_text_color(ui_RollerTimeZone, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerTimeZone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerTimeZone, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerTimeZone, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_RollerTimeZone, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 330);
    lv_obj_set_y(ui_Label13, 10);
    lv_label_set_text(ui_Label13, "الوقت ");
    lv_obj_set_style_text_font(ui_Label13, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label14 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label14, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label14, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label14, 255);
    lv_obj_set_y(ui_Label14, 35);
    lv_label_set_text(ui_Label14, ":");

    ui_Label15 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label15, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label15, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label15, 134);
    lv_obj_set_y(ui_Label15, 10);
    lv_label_set_text(ui_Label15, "التاريخ");
    lv_obj_set_style_text_font(ui_Label15, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label16 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label16, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label16, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label16, 312);
    lv_obj_set_y(ui_Label16, 155);
    lv_label_set_text(ui_Label16, "المنطقة الزمنية");
    lv_obj_set_style_text_font(ui_Label16, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CheckBoxAutoClock = lv_checkbox_create(ui_TabPage2);
    lv_checkbox_set_text(ui_CheckBoxAutoClock, "تلقائي");
    lv_obj_set_width(ui_CheckBoxAutoClock, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CheckBoxAutoClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CheckBoxAutoClock, 312);
    lv_obj_set_y(ui_CheckBoxAutoClock, 105);
    lv_obj_add_flag(ui_CheckBoxAutoClock, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_CheckBoxAutoClock, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_CheckBoxAutoClock, lv_color_hex(0x292831), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CheckBoxAutoClock, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_Calendar2 = lv_calendar_create(ui_TabPage2);
    lv_calendar_set_today_date(ui_Calendar2, 2025, 7, 7);
    lv_calendar_set_showed_date(ui_Calendar2, 2025, 7);
    lv_obj_t * ui_Calendar2_header = lv_calendar_header_arrow_create(ui_Calendar2);
    lv_obj_set_width(ui_Calendar2, 195);
    lv_obj_set_height(ui_Calendar2, 200);
    lv_obj_set_x(ui_Calendar2, -132);
    lv_obj_set_y(ui_Calendar2, 24);
    lv_obj_set_align(ui_Calendar2, LV_ALIGN_CENTER);

    ui_Label18 = lv_label_create(ui_TabPage2);
    lv_obj_set_width(ui_Label18, 137);
    lv_obj_set_height(ui_Label18, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label18, -166);
    lv_obj_set_y(ui_Label18, -101);
    lv_obj_set_align(ui_Label18, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label18, "YYYY-MM-DD");
    lv_obj_add_flag(ui_Label18, LV_OBJ_FLAG_CLICKABLE);     /// Flags
    lv_obj_set_style_text_align(ui_Label18, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label18, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonSettingClock = lv_btn_create(ui_TabPage2);
    lv_obj_set_width(ui_ButtonSettingClock, 60);
    lv_obj_set_height(ui_ButtonSettingClock, 30);
    lv_obj_set_x(ui_ButtonSettingClock, 134);
    lv_obj_set_y(ui_ButtonSettingClock, 116);
    lv_obj_set_align(ui_ButtonSettingClock, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonSettingClock, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonSettingClock, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label8 = lv_label_create(ui_ButtonSettingClock);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "حفظ");
    lv_obj_set_style_text_font(ui_Label8, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage3 = lv_tabview_add_tab(ui_TabView2, "المخارج");
    lv_obj_clear_flag(ui_TabPage3, LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags
    lv_obj_set_scroll_dir(ui_TabPage3, LV_DIR_VER);

    ui_Container2 = lv_obj_create(ui_TabPage3);
    lv_obj_remove_style_all(ui_Container2);
    lv_obj_set_width(ui_Container2, 480);
    lv_obj_set_height(ui_Container2, 500);
    lv_obj_set_x(ui_Container2, -1);
    lv_obj_set_y(ui_Container2, 0);
    lv_obj_set_align(ui_Container2, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Container2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Container2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_text_font(ui_Container2, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRelayInfo1 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo1, 90);
    lv_obj_set_height(ui_PanelRelayInfo1, 70);
    lv_obj_set_x(ui_PanelRelayInfo1, 320);
    lv_obj_set_y(ui_PanelRelayInfo1, 100);
    lv_obj_clear_flag(ui_PanelRelayInfo1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting1 = lv_label_create(ui_PanelRelayInfo1);
    lv_obj_set_width(ui_LabelRelayNameSetting1, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting1, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting1, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting1, "بدون اسم");

    ui_PanelRelayInfo2 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo2, 90);
    lv_obj_set_height(ui_PanelRelayInfo2, 70);
    lv_obj_set_x(ui_PanelRelayInfo2, 220);
    lv_obj_set_y(ui_PanelRelayInfo2, 100);
    lv_obj_clear_flag(ui_PanelRelayInfo2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting2 = lv_label_create(ui_PanelRelayInfo2);
    lv_obj_set_width(ui_LabelRelayNameSetting2, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting2, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting2, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting2, "بدون اسم");

    ui_PanelRelayInfo3 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo3, 90);
    lv_obj_set_height(ui_PanelRelayInfo3, 70);
    lv_obj_set_x(ui_PanelRelayInfo3, 120);
    lv_obj_set_y(ui_PanelRelayInfo3, 100);
    lv_obj_clear_flag(ui_PanelRelayInfo3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting3 = lv_label_create(ui_PanelRelayInfo3);
    lv_obj_set_width(ui_LabelRelayNameSetting3, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting3, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting3, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting3, "بدون اسم");

    ui_PanelRelayInfo4 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo4, 90);
    lv_obj_set_height(ui_PanelRelayInfo4, 70);
    lv_obj_set_x(ui_PanelRelayInfo4, 20);
    lv_obj_set_y(ui_PanelRelayInfo4, 100);
    lv_obj_clear_flag(ui_PanelRelayInfo4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting4 = lv_label_create(ui_PanelRelayInfo4);
    lv_obj_set_width(ui_LabelRelayNameSetting4, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting4, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting4, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting4, "بدون اسم");

    ui_PanelRelayInfo5 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo5, 90);
    lv_obj_set_height(ui_PanelRelayInfo5, 70);
    lv_obj_set_x(ui_PanelRelayInfo5, 320);
    lv_obj_set_y(ui_PanelRelayInfo5, 180);
    lv_obj_clear_flag(ui_PanelRelayInfo5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting5 = lv_label_create(ui_PanelRelayInfo5);
    lv_obj_set_width(ui_LabelRelayNameSetting5, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting5, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting5, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting5, "بدون اسم");

    ui_PanelRelayInfo6 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo6, 90);
    lv_obj_set_height(ui_PanelRelayInfo6, 70);
    lv_obj_set_x(ui_PanelRelayInfo6, 220);
    lv_obj_set_y(ui_PanelRelayInfo6, 180);
    lv_obj_clear_flag(ui_PanelRelayInfo6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo6, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting6 = lv_label_create(ui_PanelRelayInfo6);
    lv_obj_set_width(ui_LabelRelayNameSetting6, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting6, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting6, "بدون اسم");

    ui_PanelRelayInfo7 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo7, 90);
    lv_obj_set_height(ui_PanelRelayInfo7, 70);
    lv_obj_set_x(ui_PanelRelayInfo7, 120);
    lv_obj_set_y(ui_PanelRelayInfo7, 180);
    lv_obj_clear_flag(ui_PanelRelayInfo7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo7, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting7 = lv_label_create(ui_PanelRelayInfo7);
    lv_obj_set_width(ui_LabelRelayNameSetting7, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting7, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting7, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting7, "بدون اسم");

    ui_PanelRelayInfo8 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelayInfo8, 90);
    lv_obj_set_height(ui_PanelRelayInfo8, 70);
    lv_obj_set_x(ui_PanelRelayInfo8, 20);
    lv_obj_set_y(ui_PanelRelayInfo8, 180);
    lv_obj_clear_flag(ui_PanelRelayInfo8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PanelRelayInfo8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRelayInfo8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRelayInfo8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRelayInfo8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelRelayNameSetting8 = lv_label_create(ui_PanelRelayInfo8);
    lv_obj_set_width(ui_LabelRelayNameSetting8, 50);
    lv_obj_set_height(ui_LabelRelayNameSetting8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelRelayNameSetting8, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelRelayNameSetting8, LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_LabelRelayNameSetting8, "بدون اسم");

    ui_PanelRelaySetting = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_PanelRelaySetting, 400);
    lv_obj_set_height(ui_PanelRelaySetting, 80);
    lv_obj_set_x(ui_PanelRelaySetting, -25);
    lv_obj_set_y(ui_PanelRelaySetting, 0);
    lv_obj_set_align(ui_PanelRelaySetting, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelRelaySetting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_PanelRelaySetting, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DropdownRelayNumber = lv_dropdown_create(ui_PanelRelaySetting);
    lv_dropdown_set_options(ui_DropdownRelayNumber, "1\n2\n3\n4\n5\n6\n7\n8");
    lv_obj_set_width(ui_DropdownRelayNumber, 53);
    lv_obj_set_height(ui_DropdownRelayNumber, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DropdownRelayNumber, 135);
    lv_obj_set_y(ui_DropdownRelayNumber, 8);
    lv_obj_set_align(ui_DropdownRelayNumber, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DropdownRelayNumber, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_DropdownRelayNumber, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaRelayName = lv_textarea_create(ui_PanelRelaySetting);
    lv_obj_set_width(ui_TextAreaRelayName, 200);
    lv_obj_set_height(ui_TextAreaRelayName, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_TextAreaRelayName, 0);
    lv_obj_set_y(ui_TextAreaRelayName, 6);
    lv_obj_set_align(ui_TextAreaRelayName, LV_ALIGN_CENTER);
    lv_textarea_set_max_length(ui_TextAreaRelayName, 15);
    lv_textarea_set_placeholder_text(ui_TextAreaRelayName, "اسم الريله");
    lv_textarea_set_one_line(ui_TextAreaRelayName, true);
    lv_obj_set_style_text_align(ui_TextAreaRelayName, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextAreaRelayName, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_TextAreaRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TextAreaRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TextAreaRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TextAreaRelayName, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ButtonRelaySave = lv_btn_create(ui_PanelRelaySetting);
    lv_obj_set_width(ui_ButtonRelaySave, 50);
    lv_obj_set_height(ui_ButtonRelaySave, 40);
    lv_obj_set_x(ui_ButtonRelaySave, -133);
    lv_obj_set_y(ui_ButtonRelaySave, 6);
    lv_obj_set_align(ui_ButtonRelaySave, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ButtonRelaySave, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_ButtonRelaySave, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_ButtonRelaySave);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "حفظ");

    ui_Panel2 = lv_obj_create(ui_Container2);
    lv_obj_set_width(ui_Panel2, 390);
    lv_obj_set_height(ui_Panel2, 250);
    lv_obj_set_x(ui_Panel2, -25);
    lv_obj_set_y(ui_Panel2, 260);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label39 = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_Label39, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label39, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label39, 118);
    lv_obj_set_y(ui_Label39, -100);
    lv_obj_set_align(ui_Label39, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label39, "إعدادات التحكم اليدوي");
    lv_obj_set_style_text_font(ui_Label39, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, 90);
    lv_obj_set_height(ui_Container3, 75);
    lv_obj_set_x(ui_Container3, 300);
    lv_obj_set_y(ui_Container3, 50);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay1 = lv_switch_create(ui_Container3);
    lv_obj_set_width(ui_SwitchAutoRelay1, 50);
    lv_obj_set_height(ui_SwitchAutoRelay1, 25);
    lv_obj_set_align(ui_SwitchAutoRelay1, LV_ALIGN_CENTER);

    ui_LabelControlState1 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelControlState1, 50);
    lv_obj_set_height(ui_LabelControlState1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState1, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LabelControlState1, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelControlState1, "تلقائي");
    lv_obj_set_style_text_align(ui_LabelControlState1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelControlState1, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container4 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container4);
    lv_obj_set_width(ui_Container4, 90);
    lv_obj_set_height(ui_Container4, 75);
    lv_obj_set_x(ui_Container4, 200);
    lv_obj_set_y(ui_Container4, 50);
    lv_obj_clear_flag(ui_Container4, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay2 = lv_switch_create(ui_Container4);
    lv_obj_set_width(ui_SwitchAutoRelay2, 50);
    lv_obj_set_height(ui_SwitchAutoRelay2, 25);
    lv_obj_set_align(ui_SwitchAutoRelay2, LV_ALIGN_CENTER);

    ui_LabelControlState2 = lv_label_create(ui_Container4);
    lv_obj_set_width(ui_LabelControlState2, 50);
    lv_obj_set_height(ui_LabelControlState2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState2, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LabelControlState2, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelControlState2, "تلقائي");
    lv_obj_set_style_text_align(ui_LabelControlState2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelControlState2, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container5 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container5);
    lv_obj_set_width(ui_Container5, 90);
    lv_obj_set_height(ui_Container5, 75);
    lv_obj_set_x(ui_Container5, 100);
    lv_obj_set_y(ui_Container5, 50);
    lv_obj_clear_flag(ui_Container5, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay3 = lv_switch_create(ui_Container5);
    lv_obj_set_width(ui_SwitchAutoRelay3, 50);
    lv_obj_set_height(ui_SwitchAutoRelay3, 25);
    lv_obj_set_align(ui_SwitchAutoRelay3, LV_ALIGN_CENTER);

    ui_LabelControlState3 = lv_label_create(ui_Container5);
    lv_obj_set_width(ui_LabelControlState3, 50);
    lv_obj_set_height(ui_LabelControlState3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState3, LV_ALIGN_BOTTOM_MID);
    lv_label_set_long_mode(ui_LabelControlState3, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelControlState3, "تلقائي");
    lv_obj_set_style_text_align(ui_LabelControlState3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelControlState3, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container6 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container6);
    lv_obj_set_width(ui_Container6, 90);
    lv_obj_set_height(ui_Container6, 75);
    lv_obj_set_x(ui_Container6, 0);
    lv_obj_set_y(ui_Container6, 50);
    lv_obj_clear_flag(ui_Container6, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay4 = lv_switch_create(ui_Container6);
    lv_obj_set_width(ui_SwitchAutoRelay4, 50);
    lv_obj_set_height(ui_SwitchAutoRelay4, 25);
    lv_obj_set_align(ui_SwitchAutoRelay4, LV_ALIGN_CENTER);

    ui_LabelControlState4 = lv_label_create(ui_Container6);
    lv_obj_set_width(ui_LabelControlState4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControlState4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState4, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControlState4, "تلقائي");
    lv_obj_set_style_text_font(ui_LabelControlState4, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container7 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container7);
    lv_obj_set_width(ui_Container7, 90);
    lv_obj_set_height(ui_Container7, 75);
    lv_obj_set_x(ui_Container7, 300);
    lv_obj_set_y(ui_Container7, 150);
    lv_obj_clear_flag(ui_Container7, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay5 = lv_switch_create(ui_Container7);
    lv_obj_set_width(ui_SwitchAutoRelay5, 50);
    lv_obj_set_height(ui_SwitchAutoRelay5, 25);
    lv_obj_set_align(ui_SwitchAutoRelay5, LV_ALIGN_CENTER);

    ui_LabelControlState5 = lv_label_create(ui_Container7);
    lv_obj_set_width(ui_LabelControlState5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControlState5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState5, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControlState5, "تلقائي");
    lv_obj_set_style_text_font(ui_LabelControlState5, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container8 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container8);
    lv_obj_set_width(ui_Container8, 90);
    lv_obj_set_height(ui_Container8, 75);
    lv_obj_set_x(ui_Container8, 200);
    lv_obj_set_y(ui_Container8, 150);
    lv_obj_clear_flag(ui_Container8, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay6 = lv_switch_create(ui_Container8);
    lv_obj_set_width(ui_SwitchAutoRelay6, 50);
    lv_obj_set_height(ui_SwitchAutoRelay6, 25);
    lv_obj_set_align(ui_SwitchAutoRelay6, LV_ALIGN_CENTER);

    ui_LabelControlState6 = lv_label_create(ui_Container8);
    lv_obj_set_width(ui_LabelControlState6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControlState6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState6, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControlState6, "تلقائي");
    lv_obj_set_style_text_font(ui_LabelControlState6, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container9 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container9);
    lv_obj_set_width(ui_Container9, 90);
    lv_obj_set_height(ui_Container9, 75);
    lv_obj_set_x(ui_Container9, 100);
    lv_obj_set_y(ui_Container9, 150);
    lv_obj_clear_flag(ui_Container9, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay7 = lv_switch_create(ui_Container9);
    lv_obj_set_width(ui_SwitchAutoRelay7, 50);
    lv_obj_set_height(ui_SwitchAutoRelay7, 25);
    lv_obj_set_align(ui_SwitchAutoRelay7, LV_ALIGN_CENTER);

    ui_LabelControlState7 = lv_label_create(ui_Container9);
    lv_obj_set_width(ui_LabelControlState7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControlState7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState7, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControlState7, "تلقائي");
    lv_obj_set_style_text_font(ui_LabelControlState7, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container10 = lv_obj_create(ui_Panel2);
    lv_obj_remove_style_all(ui_Container10);
    lv_obj_set_width(ui_Container10, 90);
    lv_obj_set_height(ui_Container10, 75);
    lv_obj_set_x(ui_Container10, 0);
    lv_obj_set_y(ui_Container10, 150);
    lv_obj_clear_flag(ui_Container10, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_SwitchAutoRelay8 = lv_switch_create(ui_Container10);
    lv_obj_set_width(ui_SwitchAutoRelay8, 50);
    lv_obj_set_height(ui_SwitchAutoRelay8, 25);
    lv_obj_set_align(ui_SwitchAutoRelay8, LV_ALIGN_CENTER);

    ui_LabelControlState8 = lv_label_create(ui_Container10);
    lv_obj_set_width(ui_LabelControlState8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelControlState8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelControlState8, LV_ALIGN_BOTTOM_MID);
    lv_label_set_text(ui_LabelControlState8, "تلقائي");
    lv_obj_set_style_text_font(ui_LabelControlState8, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TabPage4 = lv_tabview_add_tab(ui_TabView2, "الشبكة");
    lv_obj_clear_flag(ui_TabPage4, LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);      /// Flags

    ui_Button6 = lv_btn_create(ui_TabPage4);
    lv_obj_set_width(ui_Button6, 75);
    lv_obj_set_height(ui_Button6, 25);
    lv_obj_set_x(ui_Button6, 350);
    lv_obj_set_y(ui_Button6, 15);
    lv_obj_add_flag(ui_Button6, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label10 = lv_label_create(ui_Button6);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "تحديث");
    lv_obj_set_style_text_font(ui_Label10, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label30 = lv_label_create(ui_TabPage4);
    lv_obj_set_width(ui_Label30, 150);
    lv_obj_set_height(ui_Label30, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label30, 30);
    lv_obj_set_y(ui_Label30, 15);
    lv_label_set_text(ui_Label30, "");
    lv_obj_set_style_text_align(ui_Label30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label30, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardSSIDPassword = lv_keyboard_create(ui_TabPage4);
    lv_obj_set_width(ui_KeyboardSSIDPassword, 444);
    lv_obj_set_height(ui_KeyboardSSIDPassword, 130);
    lv_obj_set_x(ui_KeyboardSSIDPassword, -14);
    lv_obj_set_y(ui_KeyboardSSIDPassword, 14);
    lv_obj_add_flag(ui_KeyboardSSIDPassword, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_pad_left(ui_KeyboardSSIDPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardSSIDPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardSSIDPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardSSIDPassword, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_KeyboardSSIDPassword, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_PanelSSIDPassword = lv_obj_create(ui_TabPage4);
    lv_obj_set_width(ui_PanelSSIDPassword, 400);
    lv_obj_set_height(ui_PanelSSIDPassword, 130);
    lv_obj_set_x(ui_PanelSSIDPassword, 0);
    lv_obj_set_y(ui_PanelSSIDPassword, -70);
    lv_obj_set_align(ui_PanelSSIDPassword, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelSSIDPassword, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelSSIDPassword, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelSSID = lv_label_create(ui_PanelSSIDPassword);
    lv_obj_set_width(ui_LabelSSID, 200);
    lv_obj_set_height(ui_LabelSSID, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelSSID, 47);
    lv_obj_set_y(ui_LabelSSID, -44);
    lv_obj_set_align(ui_LabelSSID, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_LabelSSID, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_LabelSSID, "");
    lv_obj_set_style_text_font(ui_LabelSSID, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TextAreaSSIPassword = lv_textarea_create(ui_PanelSSIDPassword);
    lv_obj_set_width(ui_TextAreaSSIPassword, 248);
    lv_obj_set_height(ui_TextAreaSSIPassword, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_TextAreaSSIPassword, 66);
    lv_obj_set_y(ui_TextAreaSSIPassword, -7);
    lv_obj_set_align(ui_TextAreaSSIPassword, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextAreaSSIPassword, "SSID password ...");
    lv_textarea_set_one_line(ui_TextAreaSSIPassword, true);
    lv_textarea_set_password_mode(ui_TextAreaSSIPassword, true);
    lv_obj_set_style_text_font(ui_TextAreaSSIPassword, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TextAreaSSIPassword, &lv_font_montserrat_14, LV_PART_SELECTED | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TextAreaSSIPassword, &lv_font_montserrat_14, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_Button7 = lv_btn_create(ui_PanelSSIDPassword);
    lv_obj_set_width(ui_Button7, 50);
    lv_obj_set_height(ui_Button7, 25);
    lv_obj_set_x(ui_Button7, 81);
    lv_obj_set_y(ui_Button7, 39);
    lv_obj_set_align(ui_Button7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button7, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label34 = lv_label_create(ui_Button7);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "أتصال");
    lv_obj_set_style_text_font(ui_Label34, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button8 = lv_btn_create(ui_PanelSSIDPassword);
    lv_obj_set_width(ui_Button8, 50);
    lv_obj_set_height(ui_Button8, 25);
    lv_obj_set_x(ui_Button8, 147);
    lv_obj_set_y(ui_Button8, 38);
    lv_obj_set_align(ui_Button8, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button8, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label33 = lv_label_create(ui_Button8);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "إلغاء");
    lv_obj_set_style_text_font(ui_Label33, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_KeyboardRelayName = lv_keyboard_create(ui_settingContentContainer);
    lv_keyboard_set_mode(ui_KeyboardRelayName, LV_KEYBOARD_MODE_SPECIAL);
    lv_obj_set_width(ui_KeyboardRelayName, 440);
    lv_obj_set_height(ui_KeyboardRelayName, 130);
    lv_obj_set_x(ui_KeyboardRelayName, -18);
    lv_obj_set_y(ui_KeyboardRelayName, 0);
    lv_obj_add_flag(ui_KeyboardRelayName, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_KeyboardRelayName,
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_KeyboardRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_KeyboardRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_KeyboardRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_KeyboardRelayName, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_KeyboardRelayName, &ui_font_NotoSans14, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_programContentContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_programContentContainer);
    lv_obj_set_width(ui_programContentContainer, 480);
    lv_obj_set_height(ui_programContentContainer, 320);
    lv_obj_set_align(ui_programContentContainer, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_programContentContainer, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_programContentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Button1 = lv_btn_create(ui_programContentContainer);
    lv_obj_set_width(ui_Button1, 80);
    lv_obj_set_height(ui_Button1, 35);
    lv_obj_set_x(ui_Button1, 70);
    lv_obj_set_y(ui_Button1, 25);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "إضافة برمجية");
    lv_obj_set_style_text_font(ui_Label41, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button2 = lv_btn_create(ui_programContentContainer);
    lv_obj_set_width(ui_Button2, 80);
    lv_obj_set_height(ui_Button2, 35);
    lv_obj_set_x(ui_Button2, 350);
    lv_obj_set_y(ui_Button2, 25);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0xF6204A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "حذف البرمجيات");
    lv_obj_set_style_text_font(ui_Label1, &ui_font_NotoSans12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ContainerProgram = lv_obj_create(ui_programContentContainer);
    lv_obj_remove_style_all(ui_ContainerProgram);
    lv_obj_set_width(ui_ContainerProgram, 440);
    lv_obj_set_height(ui_ContainerProgram, 250);
    lv_obj_set_x(ui_ContainerProgram, 0);
    lv_obj_set_y(ui_ContainerProgram, 70);
    lv_obj_clear_flag(ui_ContainerProgram, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_mainContentContainer = lv_obj_create(ui_Screen1);
    lv_obj_remove_style_all(ui_mainContentContainer);
    lv_obj_set_width(ui_mainContentContainer, 480);
    lv_obj_set_height(ui_mainContentContainer, 320);
    lv_obj_set_x(ui_mainContentContainer, 5);
    lv_obj_set_y(ui_mainContentContainer, 9);
    lv_obj_set_align(ui_mainContentContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_mainContentContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_mainContentContainer, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image8 = lv_img_create(ui_mainContentContainer);
    lv_img_set_src(ui_Image8, &ui_img_mosuqe_png);
    lv_obj_set_width(ui_Image8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Image8, 71);
    lv_obj_set_y(ui_Image8, 39);
    lv_obj_add_flag(ui_Image8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel1 = lv_obj_create(ui_mainContentContainer);
    lv_obj_set_width(ui_Panel1, 59);
    lv_obj_set_height(ui_Panel1, 264);
    lv_obj_set_x(ui_Panel1, 5);
    lv_obj_set_y(ui_Panel1, 46);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Panel1, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label17 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label17, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label17, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label17, 0);
    lv_obj_set_y(ui_Label17, -20);
    lv_obj_set_align(ui_Label17, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label17, "الفجر");
    lv_obj_set_style_text_color(ui_Label17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label17, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label17, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label19 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label19, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label19, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label19, 0);
    lv_obj_set_y(ui_Label19, 5);
    lv_obj_set_align(ui_Label19, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label19, "06:43");
    lv_obj_set_style_text_color(ui_Label19, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label19, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label19, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label20 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label20, 0);
    lv_obj_set_y(ui_Label20, 60);
    lv_obj_set_align(ui_Label20, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label20, "الظهر");
    lv_obj_set_style_text_color(ui_Label20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label20, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label20, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label21 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label21, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label21, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label21, 0);
    lv_obj_set_y(ui_Label21, 85);
    lv_label_set_text(ui_Label21, "13:38");
    lv_obj_set_style_text_color(ui_Label21, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label21, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label22 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label22, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label22, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label22, 0);
    lv_obj_set_y(ui_Label22, 100);
    lv_obj_set_align(ui_Label22, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label22, "العصر");
    lv_obj_set_style_text_color(ui_Label22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label22, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label23 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label23, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label23, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label23, 0);
    lv_obj_set_y(ui_Label23, 125);
    lv_obj_set_align(ui_Label23, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label23, "13:38");
    lv_obj_set_style_text_color(ui_Label23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label23, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, 0);
    lv_obj_set_y(ui_Label24, 140);
    lv_obj_set_align(ui_Label24, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label24, "المغرب");
    lv_obj_set_style_text_color(ui_Label24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label24, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label25 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 0);
    lv_obj_set_y(ui_Label25, 165);
    lv_obj_set_align(ui_Label25, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label25, "18:44");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label25, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, 0);
    lv_obj_set_y(ui_Label26, 180);
    lv_obj_set_align(ui_Label26, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label26, "العشاء");
    lv_obj_set_style_text_color(ui_Label26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label26, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label27 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, 0);
    lv_obj_set_y(ui_Label27, 205);
    lv_obj_set_align(ui_Label27, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label27, "18:44");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label27, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label28 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label28, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label28, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label28, 0);
    lv_obj_set_y(ui_Label28, 20);
    lv_obj_set_align(ui_Label28, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label28, "الشروق");
    lv_obj_set_style_text_color(ui_Label28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label28, &ui_font_NotoSans10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label29 = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label29, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label29, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label29, 0);
    lv_obj_set_y(ui_Label29, 45);
    lv_obj_set_align(ui_Label29, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label29, "06:43");
    lv_obj_set_style_text_color(ui_Label29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label29, &lv_font_montserrat_12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_mainContentContainer);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, 324);
    lv_obj_set_height(ui_Container1, 43);
    lv_obj_set_x(ui_Container1, 57);
    lv_obj_set_y(ui_Container1, 0);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label43 = lv_label_create(ui_Container1);
    lv_obj_set_width(ui_Label43, 150);
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, 69);
    lv_obj_set_y(ui_Label43, -4);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_Label43, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_Label43, "الأحد , تموز 2025");
    lv_obj_set_style_text_align(ui_Label43, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label43, &ui_font_NotoSans20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_imageNoWiFi = lv_img_create(ui_mainContentContainer);
    lv_img_set_src(ui_imageNoWiFi, &ui_img_nowifi_png);
    lv_obj_set_width(ui_imageNoWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageNoWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageNoWiFi, 10);
    lv_obj_set_y(ui_imageNoWiFi, 7);
    lv_obj_add_flag(ui_imageNoWiFi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageNoWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imageWiFi = lv_img_create(ui_mainContentContainer);
    lv_img_set_src(ui_imageWiFi, &ui_img_wifi_png);
    lv_obj_set_width(ui_imageWiFi, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_imageWiFi, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_imageWiFi, 45);
    lv_obj_set_y(ui_imageWiFi, 7);
    lv_obj_add_flag(ui_imageWiFi, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imageWiFi, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_labelClock = lv_label_create(ui_mainContentContainer);
    lv_obj_set_width(ui_labelClock, 68);
    lv_obj_set_height(ui_labelClock, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_labelClock, 189);
    lv_obj_set_y(ui_labelClock, -140);
    lv_obj_set_align(ui_labelClock, LV_ALIGN_CENTER);
    lv_label_set_text(ui_labelClock, "00:00");
    lv_obj_set_style_text_align(ui_labelClock, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_labelClock, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelInfo = lv_obj_create(ui_mainContentContainer);
    lv_obj_set_width(ui_PanelInfo, 300);
    lv_obj_set_height(ui_PanelInfo, 200);
    lv_obj_set_align(ui_PanelInfo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PanelInfo, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_PanelInfo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label4 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, 54);
    lv_obj_set_y(ui_Label4, -70);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "الإصدار الحالي للبرنامج");
    lv_obj_set_style_text_font(ui_Label4, &ui_font_NotoSans14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -83);
    lv_obj_set_y(ui_Label5, -70);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "1.0.0V");
    lv_obj_set_style_text_font(ui_Label5, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label37 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_Label37, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label37, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label37, 0);
    lv_obj_set_y(ui_Label37, -20);
    lv_obj_set_align(ui_Label37, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label37, "قم بنسخ هذا الرمز إلى التطبيق");
    lv_obj_set_style_text_font(ui_Label37, &ui_font_NotoSans18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label38 = lv_label_create(ui_PanelInfo);
    lv_obj_set_width(ui_Label38, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label38, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label38, 3);
    lv_obj_set_y(ui_Label38, 38);
    lv_obj_set_align(ui_Label38, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label38, "xxxxxxxxxxxx");
    lv_obj_set_style_text_font(ui_Label38, &lv_font_montserrat_30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_mainScreenButton = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_mainScreenButton, 33);
    lv_obj_set_height(ui_mainScreenButton, 33);
    lv_obj_set_x(ui_mainScreenButton, 447);
    lv_obj_set_y(ui_mainScreenButton, 92);
    lv_obj_clear_flag(ui_mainScreenButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_mainScreenButton, lv_color_hex(0x2666DE), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_mainScreenButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_mainScreenButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image4 = lv_img_create(ui_mainScreenButton);
    lv_img_set_src(ui_Image4, &ui_img_650607941);
    lv_obj_set_width(ui_Image4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image4, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_programSettingButton = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_programSettingButton, 33);
    lv_obj_set_height(ui_programSettingButton, 33);
    lv_obj_set_x(ui_programSettingButton, 447);
    lv_obj_set_y(ui_programSettingButton, 130);
    lv_obj_clear_flag(ui_programSettingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_programSettingButton, lv_color_hex(0x606162), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_programSettingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_programSettingButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image5 = lv_img_create(ui_programSettingButton);
    lv_img_set_src(ui_Image5, &ui_img_1867271658);
    lv_obj_set_width(ui_Image5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image5, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_aboutButton = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_aboutButton, 33);
    lv_obj_set_height(ui_aboutButton, 33);
    lv_obj_set_x(ui_aboutButton, 447);
    lv_obj_set_y(ui_aboutButton, 168);
    lv_obj_clear_flag(ui_aboutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_aboutButton, lv_color_hex(0x606162), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_aboutButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_aboutButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image6 = lv_img_create(ui_aboutButton);
    lv_img_set_src(ui_Image6, &ui_img_help_png);
    lv_obj_set_width(ui_Image6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image6, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image6, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image6, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settingButton = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_settingButton, 33);
    lv_obj_set_height(ui_settingButton, 33);
    lv_obj_set_x(ui_settingButton, 447);
    lv_obj_set_y(ui_settingButton, 208);
    lv_obj_clear_flag(ui_settingButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settingButton, lv_color_hex(0x606162), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settingButton, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(ui_settingButton, LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image7 = lv_img_create(ui_settingButton);
    lv_img_set_src(ui_Image7, &ui_img_1308353594);
    lv_obj_set_width(ui_Image7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image7, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_Calendar2, ui_event_Calendar2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Label18, ui_event_Label18, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonSettingClock, ui_event_ButtonSettingClock, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TextAreaRelayName, ui_event_TextAreaRelayName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ButtonRelaySave, ui_event_ButtonRelaySave, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay1, ui_event_SwitchAutoRelay1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay2, ui_event_SwitchAutoRelay2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay3, ui_event_SwitchAutoRelay3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay4, ui_event_SwitchAutoRelay4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay5, ui_event_SwitchAutoRelay5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay6, ui_event_SwitchAutoRelay6, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay7, ui_event_SwitchAutoRelay7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SwitchAutoRelay8, ui_event_SwitchAutoRelay8, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button6, ui_event_Button6, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardSSIDPassword, ui_TextAreaSSIPassword);
    lv_obj_add_event_cb(ui_TextAreaSSIPassword, ui_event_TextAreaSSIPassword, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button7, ui_event_Button7, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button8, ui_event_Button8, LV_EVENT_ALL, NULL);
    lv_keyboard_set_textarea(ui_KeyboardRelayName, ui_TextAreaRelayName);
    lv_obj_add_event_cb(ui_KeyboardRelayName, ui_event_KeyboardRelayName, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_mainScreenButton, ui_event_mainScreenButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_programSettingButton, ui_event_programSettingButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_aboutButton, ui_event_aboutButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settingButton, ui_event_settingButton, LV_EVENT_ALL, NULL);

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_settingContentContainer = NULL;
    ui_TabView2 = NULL;
    ui_TabPage2 = NULL;
    ui_rollerMinuteSetting = NULL;
    ui_rollerHourSetting = NULL;
    ui_RollerTimeZone = NULL;
    ui_Label13 = NULL;
    ui_Label14 = NULL;
    ui_Label15 = NULL;
    ui_Label16 = NULL;
    ui_CheckBoxAutoClock = NULL;
    ui_Calendar2 = NULL;
    ui_Label18 = NULL;
    ui_ButtonSettingClock = NULL;
    ui_Label8 = NULL;
    ui_TabPage3 = NULL;
    ui_Container2 = NULL;
    ui_PanelRelayInfo1 = NULL;
    ui_LabelRelayNameSetting1 = NULL;
    ui_PanelRelayInfo2 = NULL;
    ui_LabelRelayNameSetting2 = NULL;
    ui_PanelRelayInfo3 = NULL;
    ui_LabelRelayNameSetting3 = NULL;
    ui_PanelRelayInfo4 = NULL;
    ui_LabelRelayNameSetting4 = NULL;
    ui_PanelRelayInfo5 = NULL;
    ui_LabelRelayNameSetting5 = NULL;
    ui_PanelRelayInfo6 = NULL;
    ui_LabelRelayNameSetting6 = NULL;
    ui_PanelRelayInfo7 = NULL;
    ui_LabelRelayNameSetting7 = NULL;
    ui_PanelRelayInfo8 = NULL;
    ui_LabelRelayNameSetting8 = NULL;
    ui_PanelRelaySetting = NULL;
    ui_DropdownRelayNumber = NULL;
    ui_TextAreaRelayName = NULL;
    ui_ButtonRelaySave = NULL;
    ui_Label2 = NULL;
    ui_Panel2 = NULL;
    ui_Label39 = NULL;
    ui_Container3 = NULL;
    ui_SwitchAutoRelay1 = NULL;
    ui_LabelControlState1 = NULL;
    ui_Container4 = NULL;
    ui_SwitchAutoRelay2 = NULL;
    ui_LabelControlState2 = NULL;
    ui_Container5 = NULL;
    ui_SwitchAutoRelay3 = NULL;
    ui_LabelControlState3 = NULL;
    ui_Container6 = NULL;
    ui_SwitchAutoRelay4 = NULL;
    ui_LabelControlState4 = NULL;
    ui_Container7 = NULL;
    ui_SwitchAutoRelay5 = NULL;
    ui_LabelControlState5 = NULL;
    ui_Container8 = NULL;
    ui_SwitchAutoRelay6 = NULL;
    ui_LabelControlState6 = NULL;
    ui_Container9 = NULL;
    ui_SwitchAutoRelay7 = NULL;
    ui_LabelControlState7 = NULL;
    ui_Container10 = NULL;
    ui_SwitchAutoRelay8 = NULL;
    ui_LabelControlState8 = NULL;
    ui_TabPage4 = NULL;
    ui_Button6 = NULL;
    ui_Label10 = NULL;
    ui_Label30 = NULL;
    ui_KeyboardSSIDPassword = NULL;
    ui_PanelSSIDPassword = NULL;
    ui_LabelSSID = NULL;
    ui_TextAreaSSIPassword = NULL;
    ui_Button7 = NULL;
    ui_Label34 = NULL;
    ui_Button8 = NULL;
    ui_Label33 = NULL;
    ui_KeyboardRelayName = NULL;
    ui_programContentContainer = NULL;
    ui_Button1 = NULL;
    ui_Label41 = NULL;
    ui_Button2 = NULL;
    ui_Label1 = NULL;
    ui_ContainerProgram = NULL;
    ui_mainContentContainer = NULL;
    ui_Image8 = NULL;
    ui_Panel1 = NULL;
    ui_Label17 = NULL;
    ui_Label19 = NULL;
    ui_Label20 = NULL;
    ui_Label21 = NULL;
    ui_Label22 = NULL;
    ui_Label23 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    ui_Label27 = NULL;
    ui_Label28 = NULL;
    ui_Label29 = NULL;
    ui_Container1 = NULL;
    ui_Label43 = NULL;
    ui_imageNoWiFi = NULL;
    ui_imageWiFi = NULL;
    ui_labelClock = NULL;
    ui_PanelInfo = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label37 = NULL;
    ui_Label38 = NULL;
    ui_mainScreenButton = NULL;
    ui_Image4 = NULL;
    ui_programSettingButton = NULL;
    ui_Image5 = NULL;
    ui_aboutButton = NULL;
    ui_Image6 = NULL;
    ui_settingButton = NULL;
    ui_Image7 = NULL;

}
