// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN1_H
#define UI_SCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen1
extern void ui_Screen1_screen_init(void);
extern void ui_Screen1_screen_destroy(void);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_settingContentContainer;
extern lv_obj_t * ui_TabView2;
extern lv_obj_t * ui_TabPage2;
extern lv_obj_t * ui_rollerMinuteSetting;
extern lv_obj_t * ui_rollerHourSetting;
extern lv_obj_t * ui_RollerTimeZone;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Label14;
extern lv_obj_t * ui_Label15;
extern lv_obj_t * ui_Label16;
extern lv_obj_t * ui_CheckBoxAutoClock;
extern void ui_event_Calendar2(lv_event_t * e);
extern lv_obj_t * ui_Calendar2;
extern void ui_event_Label18(lv_event_t * e);
extern lv_obj_t * ui_Label18;
extern void ui_event_ButtonSettingClock(lv_event_t * e);
extern lv_obj_t * ui_ButtonSettingClock;
extern lv_obj_t * ui_Label8;
extern lv_obj_t * ui_TabPage3;
extern lv_obj_t * ui_Container2;
extern lv_obj_t * ui_PanelRelayInfo1;
extern lv_obj_t * ui_LabelRelayNameSetting1;
extern lv_obj_t * ui_PanelRelayInfo2;
extern lv_obj_t * ui_LabelRelayNameSetting2;
extern lv_obj_t * ui_PanelRelayInfo3;
extern lv_obj_t * ui_LabelRelayNameSetting3;
extern lv_obj_t * ui_PanelRelayInfo4;
extern lv_obj_t * ui_LabelRelayNameSetting4;
extern lv_obj_t * ui_PanelRelayInfo5;
extern lv_obj_t * ui_LabelRelayNameSetting5;
extern lv_obj_t * ui_PanelRelayInfo6;
extern lv_obj_t * ui_LabelRelayNameSetting6;
extern lv_obj_t * ui_PanelRelayInfo7;
extern lv_obj_t * ui_LabelRelayNameSetting7;
extern lv_obj_t * ui_PanelRelayInfo8;
extern lv_obj_t * ui_LabelRelayNameSetting8;
extern lv_obj_t * ui_PanelRelaySetting;
extern lv_obj_t * ui_DropdownRelayNumber;
extern void ui_event_TextAreaRelayName(lv_event_t * e);
extern lv_obj_t * ui_TextAreaRelayName;
extern void ui_event_ButtonRelaySave(lv_event_t * e);
extern lv_obj_t * ui_ButtonRelaySave;
extern lv_obj_t * ui_Label2;
extern lv_obj_t * ui_Panel2;
extern lv_obj_t * ui_Label39;
extern lv_obj_t * ui_Container3;
extern void ui_event_SwitchAutoRelay1(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay1;
extern lv_obj_t * ui_LabelControlState1;
extern lv_obj_t * ui_Container4;
extern void ui_event_SwitchAutoRelay2(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay2;
extern lv_obj_t * ui_LabelControlState2;
extern lv_obj_t * ui_Container5;
extern void ui_event_SwitchAutoRelay3(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay3;
extern lv_obj_t * ui_LabelControlState3;
extern lv_obj_t * ui_Container6;
extern void ui_event_SwitchAutoRelay4(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay4;
extern lv_obj_t * ui_LabelControlState4;
extern lv_obj_t * ui_Container7;
extern void ui_event_SwitchAutoRelay5(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay5;
extern lv_obj_t * ui_LabelControlState5;
extern lv_obj_t * ui_Container8;
extern void ui_event_SwitchAutoRelay6(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay6;
extern lv_obj_t * ui_LabelControlState6;
extern lv_obj_t * ui_Container9;
extern void ui_event_SwitchAutoRelay7(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay7;
extern lv_obj_t * ui_LabelControlState7;
extern lv_obj_t * ui_Container10;
extern void ui_event_SwitchAutoRelay8(lv_event_t * e);
extern lv_obj_t * ui_SwitchAutoRelay8;
extern lv_obj_t * ui_LabelControlState8;
extern lv_obj_t * ui_TabPage4;
extern void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
extern lv_obj_t * ui_Label10;
extern lv_obj_t * ui_Label30;
extern lv_obj_t * ui_KeyboardSSIDPassword;
extern lv_obj_t * ui_PanelSSIDPassword;
extern lv_obj_t * ui_LabelSSID;
extern void ui_event_TextAreaSSIPassword(lv_event_t * e);
extern lv_obj_t * ui_TextAreaSSIPassword;
extern void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
extern lv_obj_t * ui_Label34;
extern void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
extern lv_obj_t * ui_Label33;
extern void ui_event_KeyboardRelayName(lv_event_t * e);
extern lv_obj_t * ui_KeyboardRelayName;
extern lv_obj_t * ui_programContentContainer;
extern lv_obj_t * ui_Button1;
extern lv_obj_t * ui_Label41;
extern lv_obj_t * ui_Button2;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_ContainerProgram;
extern lv_obj_t * ui_mainContentContainer;
extern lv_obj_t * ui_Image8;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Label17;
extern lv_obj_t * ui_Label19;
extern lv_obj_t * ui_Label20;
extern lv_obj_t * ui_Label21;
extern lv_obj_t * ui_Label22;
extern lv_obj_t * ui_Label23;
extern lv_obj_t * ui_Label24;
extern lv_obj_t * ui_Label25;
extern lv_obj_t * ui_Label26;
extern lv_obj_t * ui_Label27;
extern lv_obj_t * ui_Label28;
extern lv_obj_t * ui_Label29;
extern lv_obj_t * ui_Container1;
extern lv_obj_t * ui_Label43;
extern lv_obj_t * ui_imageNoWiFi;
extern lv_obj_t * ui_imageWiFi;
extern lv_obj_t * ui_labelClock;
extern lv_obj_t * ui_PanelInfo;
extern lv_obj_t * ui_Label4;
extern lv_obj_t * ui_Label5;
extern lv_obj_t * ui_Label37;
extern lv_obj_t * ui_Label38;
extern void ui_event_mainScreenButton(lv_event_t * e);
extern lv_obj_t * ui_mainScreenButton;
extern lv_obj_t * ui_Image4;
extern void ui_event_programSettingButton(lv_event_t * e);
extern lv_obj_t * ui_programSettingButton;
extern lv_obj_t * ui_Image5;
extern void ui_event_aboutButton(lv_event_t * e);
extern lv_obj_t * ui_aboutButton;
extern lv_obj_t * ui_Image6;
extern void ui_event_settingButton(lv_event_t * e);
extern lv_obj_t * ui_settingButton;
extern lv_obj_t * ui_Image7;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

